import { db } from "./db.js";
import * as schema from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(schema.purchaseNotifications);
  await db.delete(schema.reviews);
  await db.delete(schema.deals);
  await db.delete(schema.cartItems);
  await db.delete(schema.wishlistItems);
  await db.delete(schema.products);
  await db.delete(schema.categories);

  // Seed Categories
  const categories = [
    {
      name: "Fashion",
      slug: "fashion",
      imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800",
      description: "Trendy apparel and accessories",
    },
    {
      name: "Electronics",
      slug: "electronics",
      imageUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800",
      description: "Latest gadgets and electronics",
    },
    {
      name: "Beauty & Wellness",
      slug: "beauty-wellness",
      imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800",
      description: "Beauty and wellness products",
    },
    {
      name: "Furniture",
      slug: "furniture",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
      description: "Premium furniture for your home",
    },
    {
      name: "Food & Spices",
      slug: "food-spices",
      imageUrl: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800",
      description: "Gourmet foods and specialty items",
    },
    {
      name: "Toys & Handicrafts",
      slug: "toys-handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
      description: "Fun toys and unique crafts",
    },
    {
      name: "Pet Products",
      slug: "pet-products",
      imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
      description: "Products for your furry friends",
    },
  ];

  const insertedCategories = await db.insert(schema.categories).values(categories).returning();
  console.log(`✓ Inserted ${insertedCategories.length} categories`);

  // Seed Products - USA Lifestyle Focus (100+ products)
  const products = [
    // FASHION PRODUCTS (15 items)
    {
      name: "Classic Denim Jacket - Vintage Wash",
      description: "Premium denim, timeless style, perfect for layering all year round",
      price: "69.99",
      originalPrice: "119.99",
      discount: 42,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1543076659-9380cdf10613?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      stockCount: 45,
      tags: ["trending", "bestseller"],
      badge: "Bestseller",
      freeShipping: true,
      variants: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Women's Leather Crossbody Bag",
      description: "Genuine leather, multiple compartments, adjustable strap, versatile design",
      price: "89.99",
      originalPrice: "149.99",
      discount: 40,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600",
      rating: "4.9",
      reviewCount: 1234,
      inStock: true,
      stockCount: 32,
      tags: ["trending", "recommended"],
      badge: "Premium",
      freeShipping: true,
      variants: ["Black", "Brown", "Tan", "Navy"],
    },
    {
      name: "Men's Slim Fit Chinos",
      description: "Stretch cotton blend, modern fit, wrinkle-resistant, perfect for work or casual",
      price: "49.99",
      originalPrice: "79.99",
      discount: 38,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600",
      rating: "4.6",
      reviewCount: 567,
      inStock: true,
      freeShipping: true,
      variants: ["28", "30", "32", "34", "36", "38"],
    },
    {
      name: "Athletic Running Shoes - Lightweight",
      description: "Breathable mesh, responsive cushioning, excellent traction for all surfaces",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600",
      rating: "4.8",
      reviewCount: 2341,
      inStock: true,
      stockCount: 78,
      tags: ["bestseller", "trending"],
      badge: "Hot Deal",
      freeShipping: true,
      variants: ["7", "8", "9", "10", "11", "12", "13"],
    },
    {
      name: "Cozy Knit Sweater - Oversized",
      description: "Soft acrylic blend, relaxed fit, perfect for fall and winter layering",
      price: "54.99",
      originalPrice: "89.99",
      discount: 39,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600",
      rating: "4.7",
      reviewCount: 445,
      inStock: true,
      tags: ["recommended"],
      badge: "New",
      freeShipping: true,
      variants: ["XS", "S", "M", "L", "XL"],
    },
    {
      name: "Designer Sunglasses - Polarized",
      description: "UV400 protection, scratch-resistant lenses, stylish frames for any occasion",
      price: "39.99",
      originalPrice: "69.99",
      discount: 43,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600",
      rating: "4.5",
      reviewCount: 678,
      inStock: true,
      freeShipping: false,
      variants: ["Black", "Tortoise", "Blue", "Pink"],
    },
    {
      name: "Women's High-Waisted Jeans",
      description: "Stretch denim, flattering fit, classic five-pocket design",
      price: "59.99",
      originalPrice: "99.99",
      discount: 40,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1541840031508-326b77c9a17e?w=600",
      rating: "4.8",
      reviewCount: 1089,
      inStock: true,
      stockCount: 56,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["24", "26", "28", "30", "32", "34"],
    },
    {
      name: "Leather Belt - Genuine Full Grain",
      description: "Premium leather, solid brass buckle, ages beautifully, made in USA",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1624222247344-550fb60583d2?w=600",
      rating: "4.7",
      reviewCount: 234,
      inStock: true,
      freeShipping: false,
      variants: ["S", "M", "L", "XL"],
    },
    {
      name: "Activewear Leggings - High Performance",
      description: "Moisture-wicking fabric, compression fit, squat-proof, phone pocket",
      price: "44.99",
      originalPrice: "69.99",
      discount: 36,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600",
      rating: "4.9",
      reviewCount: 1567,
      inStock: true,
      stockCount: 89,
      tags: ["trending", "bestseller"],
      badge: "Fan Favorite",
      freeShipping: true,
      variants: ["XS", "S", "M", "L", "XL"],
    },
    {
      name: "Baseball Cap - Vintage Style",
      description: "Cotton twill, adjustable strap, unstructured crown, classic dad hat fit",
      price: "19.99",
      originalPrice: "29.99",
      discount: 33,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600",
      rating: "4.5",
      reviewCount: 892,
      inStock: true,
      freeShipping: false,
      variants: ["Black", "Navy", "Khaki", "White", "Grey"],
    },
    {
      name: "Winter Puffer Jacket - Water Resistant",
      description: "Down insulation, windproof, multiple pockets, stays warm to -20°F",
      price: "129.99",
      originalPrice: "219.99",
      discount: 41,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?w=600",
      rating: "4.8",
      reviewCount: 445,
      inStock: true,
      stockCount: 23,
      tags: ["recommended"],
      badge: "Premium",
      freeShipping: true,
      variants: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Silk Scarf - Luxury Print",
      description: "100% silk, hand-rolled edges, vibrant colors, versatile styling options",
      price: "49.99",
      originalPrice: "89.99",
      discount: 44,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600",
      rating: "4.7",
      reviewCount: 234,
      inStock: true,
      tags: ["trending"],
      freeShipping: true,
      variants: ["Floral", "Geometric", "Abstract", "Animal Print"],
    },
    {
      name: "Men's Dress Shirt - Wrinkle Free",
      description: "Cotton-poly blend, button-down collar, machine washable, professional look",
      price: "39.99",
      originalPrice: "64.99",
      discount: 38,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600",
      rating: "4.6",
      reviewCount: 678,
      inStock: true,
      freeShipping: false,
      variants: ["S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Ankle Boots - Chelsea Style",
      description: "Vegan leather, elastic side panels, cushioned insole, all-day comfort",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600",
      rating: "4.8",
      reviewCount: 567,
      inStock: true,
      stockCount: 34,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["6", "7", "8", "9", "10", "11"],
    },
    {
      name: "Yoga Tank Top - Seamless",
      description: "Buttery soft fabric, built-in bra, breathable, perfect for hot yoga",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1598522325074-042db73aa4e6?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      tags: ["trending"],
      freeShipping: false,
      variants: ["XS", "S", "M", "L", "XL"],
    },

    // ELECTRONICS PRODUCTS (15 items)
    {
      name: "Premium Audio Headphones - Wireless",
      description: "40-hour battery, active noise cancellation, premium sound quality, foldable design",
      price: "149.99",
      originalPrice: "249.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
      rating: "4.8",
      reviewCount: 3421,
      inStock: true,
      stockCount: 67,
      tags: ["trending", "bestseller"],
      badge: "Bestseller",
      freeShipping: true,
      variants: ["Black", "Silver", "Rose Gold", "Navy"],
    },
    {
      name: "Digital Fitness Tracker - GPS",
      description: "Heart rate monitor, sleep tracking, waterproof, 10-day battery, 100+ workout modes",
      price: "89.99",
      originalPrice: "149.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
      rating: "4.7",
      reviewCount: 2134,
      inStock: true,
      stockCount: 89,
      tags: ["recommended", "trending"],
      freeShipping: true,
      variants: ["Black", "White", "Blue", "Pink"],
    },
    {
      name: "Compact Wireless Speaker - Water Resistant",
      description: "360° sound, 20-hour battery, IPX7 waterproof, perfect for outdoor adventures",
      price: "49.99",
      originalPrice: "79.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600",
      rating: "4.6",
      reviewCount: 1567,
      inStock: true,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["Black", "Blue", "Red", "Green"],
    },
    {
      name: "Universal Multi-Port Hub - 7-in-1",
      description: "4K HDMI, USB 3.0 ports, SD card reader, 100W power delivery, aluminum design",
      price: "39.99",
      originalPrice: "69.99",
      discount: 43,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      freeShipping: false,
      variants: ["Space Grey", "Silver"],
    },
    {
      name: "HD Web Camera - Auto Focus",
      description: "1080p/60fps, built-in mic, adjustable brightness, plug-and-play, perfect for streaming",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=600",
      rating: "4.8",
      reviewCount: 678,
      inStock: true,
      stockCount: 45,
      tags: ["trending"],
      freeShipping: true,
      variants: ["Standard", "With Ring Light"],
    },
    {
      name: "Fast Wireless Charger - 15W",
      description: "Qi-certified, works with iPhone and Android, LED indicator, sleek design",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1591290619762-0ec5fc03fe35?w=600",
      rating: "4.5",
      reviewCount: 1234,
      inStock: true,
      freeShipping: false,
      variants: ["Black", "White"],
    },
    {
      name: "Mechanical Keyboard - RGB Backlit",
      description: "Cherry MX switches, customizable RGB, programmable keys, aluminum frame",
      price: "109.99",
      originalPrice: "179.99",
      discount: 39,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=600",
      rating: "4.9",
      reviewCount: 2341,
      inStock: true,
      stockCount: 34,
      tags: ["bestseller", "trending"],
      badge: "Gaming Essential",
      freeShipping: true,
      variants: ["Blue Switch", "Red Switch", "Brown Switch"],
    },
    {
      name: "External Storage Drive - 1TB",
      description: "USB 3.1 Gen 2, up to 1050MB/s, shock-resistant, compact aluminum design",
      price: "99.99",
      originalPrice: "159.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600",
      rating: "4.8",
      reviewCount: 567,
      inStock: true,
      freeShipping: true,
      variants: ["500GB", "1TB", "2TB"],
    },
    {
      name: "WiFi LED Bulbs - 4 Pack",
      description: "WiFi enabled, 16 million colors, voice control compatible, energy efficient",
      price: "34.99",
      originalPrice: "59.99",
      discount: 42,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1604238373661-14ad70e9e5db?w=600",
      rating: "4.6",
      reviewCount: 1892,
      inStock: true,
      tags: ["trending"],
      freeShipping: false,
      variants: ["2-Pack", "4-Pack", "8-Pack"],
    },
    {
      name: "Ergonomic Wireless Mouse",
      description: "16000 DPI, 6 programmable buttons, 70-hour battery, RGB lighting",
      price: "59.99",
      originalPrice: "99.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600",
      rating: "4.7",
      reviewCount: 1234,
      inStock: true,
      stockCount: 56,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["Black", "White"],
    },
    {
      name: "Adjustable Camera Stand",
      description: "360° rotation, extends to 67 inches, Bluetooth remote, perfect for content creation",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1612198188632-c492d9e65faa?w=600",
      rating: "4.5",
      reviewCount: 892,
      inStock: true,
      freeShipping: false,
      variants: ["Standard", "With LED Ring Light"],
    },
    {
      name: "Sound Machine - Sleep Aid",
      description: "20 soothing sounds, timer function, portable, helps with sleep and focus",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1545289414-1c3cb1a06238?w=600",
      rating: "4.8",
      reviewCount: 678,
      inStock: true,
      tags: ["recommended"],
      freeShipping: false,
      variants: ["White", "Black", "Grey"],
    },
    {
      name: "Sport Camera - HD Waterproof",
      description: "4K/60fps video, 20MP photos, waterproof to 33ft, wide-angle lens, WiFi",
      price: "119.99",
      originalPrice: "199.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600",
      rating: "4.7",
      reviewCount: 567,
      inStock: true,
      stockCount: 28,
      tags: ["trending"],
      badge: "Adventure Ready",
      freeShipping: true,
      variants: ["Camera Only", "With Accessory Kit"],
    },
    {
      name: "Notebook Cooler - 6 Fan",
      description: "Adjustable height, ultra-quiet fans, LED lights, fits 12-17 inch laptops",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1585789575825-a33b8e9145f7?w=600",
      rating: "4.6",
      reviewCount: 445,
      inStock: true,
      freeShipping: false,
      variants: ["4-Fan", "6-Fan"],
    },
    {
      name: "Digital Picture Frame - WiFi",
      description: "10.1 inch HD display, touchscreen, remote access, auto-rotate, 16GB storage",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600",
      rating: "4.7",
      reviewCount: 234,
      inStock: true,
      tags: ["recommended"],
      freeShipping: true,
      variants: ["8 inch", "10 inch", "15 inch"],
    },

    // BEAUTY & WELLNESS PRODUCTS (15 items)
    {
      name: "Facial Cleansing Brush - Sonic Technology",
      description: "Waterproof, 5 speeds, gentle bristles, removes makeup and impurities",
      price: "44.99",
      originalPrice: "74.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1571875257727-256c39da42af?w=600",
      rating: "4.8",
      reviewCount: 1234,
      inStock: true,
      stockCount: 45,
      tags: ["trending", "bestseller"],
      badge: "Skincare Essential",
      freeShipping: true,
      variants: ["Pink", "White", "Blue"],
    },
    {
      name: "Vitamin C Serum - Anti-Aging",
      description: "20% vitamin C, hyaluronic acid, reduces wrinkles, brightens skin, 1 fl oz",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600",
      rating: "4.9",
      reviewCount: 2567,
      inStock: true,
      stockCount: 89,
      tags: ["bestseller", "recommended"],
      freeShipping: false,
      variants: ["1 oz", "2 oz"],
    },
    {
      name: "Hair Growth Serum - Biotin Formula",
      description: "Promotes hair growth, strengthens follicles, reduces breakage, natural ingredients",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600",
      rating: "4.7",
      reviewCount: 1892,
      inStock: true,
      tags: ["trending"],
      freeShipping: false,
      variants: ["2 oz", "4 oz"],
    },
    {
      name: "LED Face Mask - Light Therapy",
      description: "7 colors, reduces acne, anti-aging, promotes collagen, wireless design",
      price: "89.99",
      originalPrice: "149.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600",
      rating: "4.6",
      reviewCount: 678,
      inStock: true,
      stockCount: 23,
      tags: ["recommended"],
      badge: "Premium",
      freeShipping: true,
      variants: ["Standard", "With Eye Protection"],
    },
    {
      name: "Hydrating Face Moisturizer - SPF 30",
      description: "Broad spectrum protection, lightweight, non-greasy, suitable for all skin types",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600",
      rating: "4.8",
      reviewCount: 1567,
      inStock: true,
      tags: ["bestseller"],
      freeShipping: false,
      variants: ["2 oz", "4 oz", "8 oz"],
    },
    {
      name: "Makeup Brush Set - Professional 15-Piece",
      description: "Soft synthetic bristles, vegan, cruelty-free, includes storage case",
      price: "39.99",
      originalPrice: "69.99",
      discount: 43,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600",
      rating: "4.7",
      reviewCount: 2234,
      inStock: true,
      stockCount: 67,
      tags: ["trending"],
      freeShipping: true,
      variants: ["15-Piece", "24-Piece"],
    },
    {
      name: "Retinol Night Cream - Intensive Repair",
      description: "1% retinol, reduces fine lines, improves texture, hydrating formula, 1.7 oz",
      price: "34.99",
      originalPrice: "59.99",
      discount: 42,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600",
      rating: "4.9",
      reviewCount: 892,
      inStock: true,
      tags: ["bestseller", "recommended"],
      freeShipping: false,
      variants: ["1.7 oz"],
    },
    {
      name: "Jade Facial Roller - Gua Sha Set",
      description: "100% natural jade, reduces puffiness, promotes circulation, includes gua sha tool",
      price: "19.99",
      originalPrice: "34.99",
      discount: 43,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1609781148762-03e0f25c5ec4?w=600",
      rating: "4.5",
      reviewCount: 1234,
      inStock: true,
      freeShipping: false,
      variants: ["Jade", "Rose Quartz"],
    },
    {
      name: "Essential Oil Diffuser - Ultrasonic",
      description: "300ml capacity, 7 LED colors, auto shut-off, whisper quiet, wood grain finish",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600",
      rating: "4.8",
      reviewCount: 3421,
      inStock: true,
      stockCount: 78,
      tags: ["bestseller"],
      freeShipping: false,
      variants: ["Light Wood", "Dark Wood", "White"],
    },
    {
      name: "Charcoal Face Mask - Detoxifying",
      description: "Activated charcoal, removes impurities, unclogs pores, 8 oz jar",
      price: "19.99",
      originalPrice: "32.99",
      discount: 39,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600",
      rating: "4.6",
      reviewCount: 1567,
      inStock: true,
      freeShipping: false,
      variants: ["4 oz", "8 oz"],
    },
    {
      name: "Nail Care Kit - Professional 18-Piece",
      description: "Stainless steel tools, manicure and pedicure essentials, leather case",
      price: "24.99",
      originalPrice: "44.99",
      discount: 44,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      freeShipping: false,
      variants: ["18-Piece", "25-Piece"],
    },
    {
      name: "Hair Straightener - Ceramic Tourmaline",
      description: "Adjustable temperature, ionic technology, fast heating, auto shut-off",
      price: "44.99",
      originalPrice: "74.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600",
      rating: "4.8",
      reviewCount: 892,
      inStock: true,
      stockCount: 45,
      tags: ["trending"],
      freeShipping: true,
      variants: ["Standard", "Mini Travel Size"],
    },
    {
      name: "Eye Cream - Anti-Aging",
      description: "Reduces dark circles and puffiness, peptide complex, caffeine, 0.5 oz",
      price: "27.99",
      originalPrice: "44.99",
      discount: 38,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600",
      rating: "4.7",
      reviewCount: 1234,
      inStock: true,
      tags: ["recommended"],
      freeShipping: false,
      variants: ["0.5 oz", "1 oz"],
    },
    {
      name: "Lip Balm Set - Natural & Organic",
      description: "6 flavors, beeswax formula, moisturizing, no artificial ingredients",
      price: "14.99",
      originalPrice: "24.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600",
      rating: "4.6",
      reviewCount: 2341,
      inStock: true,
      freeShipping: false,
      variants: ["3-Pack", "6-Pack", "12-Pack"],
    },
    {
      name: "Bath Bombs - Spa Gift Set",
      description: "12 scents, natural ingredients, moisturizing oils, relaxing aromatherapy",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600",
      rating: "4.9",
      reviewCount: 1892,
      inStock: true,
      stockCount: 56,
      tags: ["bestseller", "trending"],
      badge: "Gift Favorite",
      freeShipping: true,
      variants: ["6-Pack", "12-Pack", "24-Pack"],
    },

    // FURNITURE PRODUCTS (12 items)
    {
      name: "Contemporary L-Shaped Sofa",
      description: "Linen fabric, reversible chaise, solid wood frame, seats 5, contemporary design",
      price: "799.99",
      originalPrice: "1299.99",
      discount: 38,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
      rating: "4.8",
      reviewCount: 234,
      inStock: true,
      stockCount: 8,
      tags: ["bestseller", "recommended"],
      badge: "Premium",
      freeShipping: true,
      variants: ["Light Grey", "Dark Grey", "Beige", "Navy"],
    },
    {
      name: "Electric Height Desk",
      description: "Motorized height adjustment, memory presets, cable management, 55 x 28 inches",
      price: "299.99",
      originalPrice: "499.99",
      discount: 40,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600",
      rating: "4.9",
      reviewCount: 892,
      inStock: true,
      stockCount: 23,
      tags: ["trending", "bestseller"],
      badge: "Office Essential",
      freeShipping: true,
      variants: ["48 inch", "55 inch", "63 inch"],
    },
    {
      name: "Mesh Office Chair - Ergonomic",
      description: "Lumbar support, adjustable armrests, breathable mesh, 360° swivel, weight capacity 300lbs",
      price: "179.99",
      originalPrice: "299.99",
      discount: 40,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
      rating: "4.7",
      reviewCount: 1567,
      inStock: true,
      stockCount: 45,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["Black", "Grey", "Blue"],
    },
    {
      name: "Modern Dresser - 6 Drawer",
      description: "Solid wood construction, smooth glide drawers, tapered legs, multiple finishes",
      price: "349.99",
      originalPrice: "599.99",
      discount: 42,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600",
      rating: "4.8",
      reviewCount: 445,
      inStock: true,
      stockCount: 12,
      tags: ["trending"],
      freeShipping: true,
      variants: ["Walnut", "Oak", "White", "Grey"],
    },
    {
      name: "5-Piece Dining Set",
      description: "Solid wood table + 4 chairs, seats 4-6, scratch-resistant finish, modern farmhouse style",
      price: "449.99",
      originalPrice: "749.99",
      discount: 40,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600",
      rating: "4.7",
      reviewCount: 345,
      inStock: true,
      stockCount: 9,
      tags: ["recommended"],
      badge: "Family Favorite",
      freeShipping: true,
      variants: ["5-Piece", "7-Piece"],
    },
    {
      name: "5-Tier Storage Shelf",
      description: "Industrial style, metal frame, wood shelves, holds 200+ books, easy assembly",
      price: "129.99",
      originalPrice: "219.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=600",
      rating: "4.6",
      reviewCount: 678,
      inStock: true,
      freeShipping: true,
      variants: ["3-Tier", "5-Tier", "7-Tier"],
    },
    {
      name: "Queen Platform Bed",
      description: "Strong wood slats, no box spring needed, under-bed storage, headboard included",
      price: "249.99",
      originalPrice: "419.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600",
      rating: "4.8",
      reviewCount: 1234,
      inStock: true,
      stockCount: 15,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["Twin", "Full", "Queen", "King"],
    },
    {
      name: "Velvet Accent Chair",
      description: "Soft velvet fabric, gold metal legs, comfortable padding, modern glam style",
      price: "189.99",
      originalPrice: "319.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600",
      rating: "4.7",
      reviewCount: 567,
      inStock: true,
      stockCount: 28,
      tags: ["trending"],
      freeShipping: true,
      variants: ["Emerald Green", "Navy Blue", "Blush Pink", "Grey"],
    },
    {
      name: "Glass Top Coffee Table",
      description: "Tempered glass, gold metal frame, geometric design, 48 x 24 inches",
      price: "159.99",
      originalPrice: "269.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=600",
      rating: "4.6",
      reviewCount: 445,
      inStock: true,
      freeShipping: true,
      variants: ["Gold", "Black", "Silver"],
    },
    {
      name: "Entertainment Center - 65 inch",
      description: "Cable management, adjustable shelves, holds up to 150lbs, barn door design",
      price: "199.99",
      originalPrice: "339.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1520034475321-cbe63696469a?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      stockCount: 19,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["Rustic Oak", "Grey Wash", "Espresso"],
    },
    {
      name: "Counter Height Stool Set",
      description: "Set of 2, swivel seat, footrest, faux leather, supports 250lbs each",
      price: "119.99",
      originalPrice: "199.99",
      discount: 40,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=600",
      rating: "4.5",
      reviewCount: 345,
      inStock: true,
      freeShipping: true,
      variants: ["Black", "Brown", "White", "Grey"],
    },
    {
      name: "2-Drawer Bedside Table",
      description: "Solid wood, smooth glide drawers, open shelf, charging station built-in",
      price: "99.99",
      originalPrice: "169.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      freeShipping: false,
      variants: ["White", "Grey", "Walnut", "Black"],
    },

    // FOOD & SPICES PRODUCTS (12 items)
    {
      name: "Organic Extra Virgin Olive Oil - Cold Pressed",
      description: "First cold press, certified organic, rich flavor, perfect for cooking and dressing",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
      rating: "4.8",
      reviewCount: 1567,
      inStock: true,
      stockCount: 89,
      tags: ["bestseller", "recommended"],
      badge: "Organic",
      freeShipping: true,
      variants: ["16.9 oz", "33.8 oz", "50.7 oz"],
    },
    {
      name: "Himalayan Pink Salt - Fine Ground",
      description: "100% pure, mineral-rich, hand-harvested, perfect for everyday cooking",
      price: "12.99",
      originalPrice: "19.99",
      discount: 35,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600",
      rating: "4.7",
      reviewCount: 2341,
      inStock: true,
      freeShipping: false,
      variants: ["1 lb", "2 lb", "5 lb"],
    },
    {
      name: "Gourmet Coffee Beans - Medium Roast",
      description: "Single origin, arabica beans, smooth flavor, freshly roasted, whole bean",
      price: "19.99",
      originalPrice: "29.99",
      discount: 33,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600",
      rating: "4.9",
      reviewCount: 3421,
      inStock: true,
      stockCount: 67,
      tags: ["trending", "bestseller"],
      badge: "Customer Favorite",
      freeShipping: false,
      variants: ["12 oz", "2 lb", "5 lb"],
    },
    {
      name: "Raw Honey - Wildflower Blend",
      description: "Unfiltered, unpasteurized, local USA honey, natural sweetener, 16 oz jar",
      price: "16.99",
      originalPrice: "26.99",
      discount: 37,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784f4f?w=600",
      rating: "4.8",
      reviewCount: 892,
      inStock: true,
      tags: ["recommended"],
      freeShipping: false,
      variants: ["8 oz", "16 oz", "32 oz"],
    },
    {
      name: "Organic Maple Syrup - Grade A",
      description: "100% pure, dark amber, rich flavor, perfect for pancakes and baking",
      price: "22.99",
      originalPrice: "34.99",
      discount: 34,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1605522561157-926aad9a29c4?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      freeShipping: true,
      variants: ["12 oz", "32 oz", "64 oz"],
    },
    {
      name: "Premium Vanilla Extract - Pure Madagascar",
      description: "100% pure extract, no artificial flavors, double-strength, baking essential",
      price: "18.99",
      originalPrice: "29.99",
      discount: 37,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600",
      rating: "4.9",
      reviewCount: 1234,
      inStock: true,
      tags: ["bestseller"],
      freeShipping: false,
      variants: ["4 oz", "8 oz", "16 oz"],
    },
    {
      name: "Italian Pasta Variety Pack",
      description: "6 authentic shapes, bronze-cut, cooks in 10 minutes, imported from Italy",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600",
      rating: "4.6",
      reviewCount: 567,
      inStock: true,
      tags: ["trending"],
      freeShipping: true,
      variants: ["6-Pack", "12-Pack"],
    },
    {
      name: "Garlic Powder - Restaurant Quality",
      description: "Pure garlic, no fillers, fine texture, intense flavor, 8 oz container",
      price: "9.99",
      originalPrice: "15.99",
      discount: 38,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600",
      rating: "4.7",
      reviewCount: 1892,
      inStock: true,
      freeShipping: false,
      variants: ["4 oz", "8 oz", "16 oz"],
    },
    {
      name: "Organic Coconut Oil - Unrefined",
      description: "Cold-pressed, virgin, versatile for cooking and beauty, 14 oz jar",
      price: "14.99",
      originalPrice: "24.99",
      discount: 40,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600",
      rating: "4.8",
      reviewCount: 2134,
      inStock: true,
      stockCount: 78,
      tags: ["bestseller"],
      freeShipping: false,
      variants: ["14 oz", "29 oz", "54 oz"],
    },
    {
      name: "Hot Sauce Variety Pack - Artisan",
      description: "5 flavors from mild to extra hot, small batch, all-natural ingredients",
      price: "29.99",
      originalPrice: "44.99",
      discount: 33,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=600",
      rating: "4.6",
      reviewCount: 445,
      inStock: true,
      tags: ["trending"],
      badge: "Spicy Favorite",
      freeShipping: true,
      variants: ["5-Pack", "10-Pack"],
    },
    {
      name: "BBQ Rub Seasoning Set - Grill Master",
      description: "4 signature blends, no MSG, perfect for ribs, brisket, chicken, pork",
      price: "19.99",
      originalPrice: "32.99",
      discount: 39,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=600",
      rating: "4.9",
      reviewCount: 1567,
      inStock: true,
      tags: ["recommended", "bestseller"],
      freeShipping: false,
      variants: ["4-Pack", "8-Pack"],
    },
    {
      name: "Organic Quinoa - Tri-Color Blend",
      description: "White, red, and black quinoa, high protein, gluten-free, 2 lb bag",
      price: "16.99",
      originalPrice: "26.99",
      discount: 37,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      freeShipping: false,
      variants: ["1 lb", "2 lb", "5 lb"],
    },

    // TOYS & HANDICRAFTS PRODUCTS (12 items)
    {
      name: "Building Blocks Set - 1000 Pieces",
      description: "Compatible with major brands, includes storage bin, encourages creativity, ages 4+",
      price: "39.99",
      originalPrice: "69.99",
      discount: 43,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600",
      rating: "4.8",
      reviewCount: 2341,
      inStock: true,
      stockCount: 56,
      tags: ["bestseller", "trending"],
      badge: "Kids Love It",
      freeShipping: true,
      variants: ["500-Piece", "1000-Piece", "2000-Piece"],
    },
    {
      name: "Art Supply Kit - 150 Pieces",
      description: "Colored pencils, markers, crayons, paper, carrying case, perfect for young artists",
      price: "34.99",
      originalPrice: "59.99",
      discount: 42,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=600",
      rating: "4.7",
      reviewCount: 1567,
      inStock: true,
      stockCount: 45,
      tags: ["recommended"],
      freeShipping: true,
      variants: ["90-Piece", "150-Piece", "200-Piece"],
    },
    {
      name: "Remote Control Car - Off-Road Monster Truck",
      description: "4WD, rechargeable battery, 25+ mph, all-terrain tires, durable design",
      price: "59.99",
      originalPrice: "99.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
      rating: "4.9",
      reviewCount: 892,
      inStock: true,
      stockCount: 34,
      tags: ["bestseller"],
      badge: "Top Rated",
      freeShipping: true,
      variants: ["Red", "Blue", "Green"],
    },
    {
      name: "Dollhouse - 3-Story Victorian",
      description: "Wooden construction, 12 rooms, includes furniture, realistic details, ages 3+",
      price: "119.99",
      originalPrice: "199.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600",
      rating: "4.8",
      reviewCount: 445,
      inStock: true,
      stockCount: 12,
      tags: ["trending"],
      badge: "Premium",
      freeShipping: true,
      variants: ["With Furniture", "Without Furniture"],
    },
    {
      name: "STEM Robot Kit - Build & Code",
      description: "Programmable robot, app-controlled, teaches coding basics, 400+ pieces, ages 8+",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1546776310-eef45dd6d63c?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      stockCount: 28,
      tags: ["recommended", "trending"],
      badge: "Educational",
      freeShipping: true,
      variants: ["Basic Kit", "Advanced Kit"],
    },
    {
      name: "Play Kitchen Set - Wooden Deluxe",
      description: "Solid wood, realistic accessories, sink, stove, fridge, encourages pretend play",
      price: "149.99",
      originalPrice: "249.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600",
      rating: "4.9",
      reviewCount: 567,
      inStock: true,
      stockCount: 8,
      tags: ["bestseller"],
      badge: "Premium Quality",
      freeShipping: true,
      variants: ["Pink", "White", "Natural Wood"],
    },
    {
      name: "Puzzle Collection - 500-1000 Pieces",
      description: "4 scenic puzzles, premium cardboard, vibrant images, family activity",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1587731556938-38755b4803a6?w=600",
      rating: "4.6",
      reviewCount: 1234,
      inStock: true,
      tags: ["recommended"],
      freeShipping: false,
      variants: ["500-Piece", "1000-Piece", "1500-Piece"],
    },
    {
      name: "Handmade Ceramic Vase - Modern Design",
      description: "Artisan-crafted, unique patterns, perfect for home decor, 10 inches tall",
      price: "44.99",
      originalPrice: "74.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600",
      rating: "4.8",
      reviewCount: 234,
      inStock: true,
      stockCount: 23,
      tags: ["trending"],
      badge: "Handmade",
      freeShipping: true,
      variants: ["Blue", "White", "Grey", "Multicolor"],
    },
    {
      name: "Board Game Bundle - Family Classics",
      description: "5 popular games, hours of entertainment, ages 6+, game night essentials",
      price: "49.99",
      originalPrice: "84.99",
      discount: 41,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1611891487540-14966e998fbf?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["3-Game Bundle", "5-Game Bundle"],
    },
    {
      name: "Macrame Wall Hanging - Boho Decor",
      description: "Handwoven cotton, 36 inches, modern bohemian style, includes hanging rod",
      price: "39.99",
      originalPrice: "69.99",
      discount: 43,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=600",
      rating: "4.8",
      reviewCount: 445,
      inStock: true,
      stockCount: 19,
      tags: ["trending"],
      badge: "Artisan Made",
      freeShipping: true,
      variants: ["24 inch", "36 inch", "48 inch"],
    },
    {
      name: "Wooden Train Set - 100 Pieces",
      description: "Compatible with major brands, includes tracks, trains, buildings, ages 3+",
      price: "54.99",
      originalPrice: "89.99",
      discount: 39,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      tags: ["recommended"],
      freeShipping: true,
      variants: ["50-Piece", "100-Piece", "150-Piece"],
    },
    {
      name: "DIY Candle Making Kit",
      description: "Makes 12 candles, includes wax, wicks, molds, fragrances, complete instructions",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1602874801006-c2b7e2f3487b?w=600",
      rating: "4.6",
      reviewCount: 567,
      inStock: true,
      stockCount: 45,
      tags: ["trending"],
      freeShipping: false,
      variants: ["Beginner Kit", "Deluxe Kit"],
    },

    // PET PRODUCTS (12 items)
    {
      name: "Premium Dry Dog Food - Grain-Free",
      description: "Real chicken, no fillers, supports healthy digestion, all life stages, 30 lb bag",
      price: "59.99",
      originalPrice: "89.99",
      discount: 33,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600",
      rating: "4.9",
      reviewCount: 3421,
      inStock: true,
      stockCount: 67,
      tags: ["bestseller", "recommended"],
      badge: "Vet Recommended",
      freeShipping: true,
      variants: ["15 lb", "30 lb", "50 lb"],
    },
    {
      name: "Cat Litter - Clumping Odor Control",
      description: "99% dust-free, unscented, tight clumping, lasts up to 30 days, 35 lb pail",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1548199569-3e5f08af2fc3?w=600",
      rating: "4.7",
      reviewCount: 2134,
      inStock: true,
      stockCount: 89,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["20 lb", "35 lb", "50 lb"],
    },
    {
      name: "Pet Water Fountain - Automatic",
      description: "2-liter capacity, triple filtration, ultra-quiet pump, encourages drinking",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1591768793355-74d04bb6608f?w=600",
      rating: "4.8",
      reviewCount: 1567,
      inStock: true,
      stockCount: 45,
      tags: ["trending", "recommended"],
      freeShipping: true,
      variants: ["1.5L", "2L", "3L"],
    },
    {
      name: "Dog Bed - Orthopedic Memory Foam",
      description: "Egg crate foam, washable cover, waterproof liner, supports joints, large size",
      price: "69.99",
      originalPrice: "119.99",
      discount: 42,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600",
      rating: "4.9",
      reviewCount: 1892,
      inStock: true,
      stockCount: 34,
      tags: ["bestseller"],
      badge: "Top Comfort",
      freeShipping: true,
      variants: ["Small", "Medium", "Large", "XL"],
    },
    {
      name: "Interactive Cat Toy Set - 20 Pieces",
      description: "Feathers, balls, mice, tunnels, variety pack, stimulates hunting instincts",
      price: "19.99",
      originalPrice: "34.99",
      discount: 43,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600",
      rating: "4.6",
      reviewCount: 2341,
      inStock: true,
      stockCount: 78,
      tags: ["trending"],
      freeShipping: false,
      variants: ["10-Piece", "20-Piece", "30-Piece"],
    },
    {
      name: "Retractable Dog Leash - 16 ft",
      description: "One-button control, reflective strip, tangle-free, for dogs up to 110 lbs",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600",
      rating: "4.7",
      reviewCount: 1234,
      inStock: true,
      freeShipping: false,
      variants: ["Small (26 lb)", "Medium (66 lb)", "Large (110 lb)"],
    },
    {
      name: "Cat Tree Tower - Multi-Level",
      description: "5 levels, sisal posts, hanging toys, condos, plush bedding, 60 inches tall",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600",
      rating: "4.8",
      reviewCount: 892,
      inStock: true,
      stockCount: 23,
      tags: ["bestseller", "recommended"],
      badge: "Cat Favorite",
      freeShipping: true,
      variants: ["48 inch", "60 inch", "72 inch"],
    },
    {
      name: "Dog Training Treats - Low Calorie",
      description: "Soft and chewy, real chicken, perfect for training, 32 oz resealable bag",
      price: "16.99",
      originalPrice: "26.99",
      discount: 37,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1623387641168-d9803ddd3f35?w=600",
      rating: "4.7",
      reviewCount: 1567,
      inStock: true,
      tags: ["trending"],
      freeShipping: false,
      variants: ["16 oz", "32 oz", "64 oz"],
    },
    {
      name: "Pet Grooming Kit - Professional",
      description: "Clippers, scissors, nail trimmer, brush, comb, quiet motor, rechargeable",
      price: "44.99",
      originalPrice: "74.99",
      discount: 40,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600",
      rating: "4.6",
      reviewCount: 678,
      inStock: true,
      stockCount: 45,
      tags: ["recommended"],
      freeShipping: true,
      variants: ["Basic", "Professional", "Deluxe"],
    },
    {
      name: "Automatic Pet Feeder - Programmable",
      description: "Holds 6 liters, 6 meals/day, portion control, voice recorder, battery backup",
      price: "54.99",
      originalPrice: "89.99",
      discount: 39,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600",
      rating: "4.8",
      reviewCount: 1234,
      inStock: true,
      stockCount: 34,
      tags: ["bestseller"],
      freeShipping: true,
      variants: ["4L", "6L", "8L"],
    },
    {
      name: "Dog Chew Toys - Durable Set",
      description: "5-piece set, non-toxic rubber, dental health, fetch and tug toys, for aggressive chewers",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1591769225440-811ad7d6eab3?w=600",
      rating: "4.7",
      reviewCount: 2134,
      inStock: true,
      tags: ["trending"],
      freeShipping: false,
      variants: ["3-Pack", "5-Pack", "8-Pack"],
    },
    {
      name: "Pet Carrier - Airline Approved",
      description: "Soft-sided, ventilated mesh, fleece bed included, fits under airline seat",
      price: "39.99",
      originalPrice: "64.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1548199569-3e5f08af2fc3?w=600",
      rating: "4.6",
      reviewCount: 892,
      inStock: true,
      stockCount: 56,
      tags: ["recommended"],
      freeShipping: true,
      variants: ["Small", "Medium", "Large"],
    },
  ];

  const insertedProducts = await db.insert(schema.products).values(products).returning();
  console.log(`✓ Inserted ${insertedProducts.length} products`);

  // Seed Flash Deals
  const deals = [
    {
      productId: insertedProducts[0].id,
      title: "Flash Sale: Classic Denim Jacket",
      endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      productId: insertedProducts[15].id,
      title: "Limited Time: Wireless Headphones",
      endsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    },
    {
      productId: insertedProducts[30].id,
      title: "Today Only: Facial Cleansing Brush",
      endsAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const insertedDeals = await db.insert(schema.deals).values(deals).returning();
  console.log(`✓ Inserted ${insertedDeals.length} deals`);

  // Seed Reviews with USA names and locations
  const reviews = [
    {
      productId: insertedProducts[0].id,
      rating: 5,
      comment: "Perfect fit and great quality! The vintage wash looks amazing.",
      customerName: "Emily Johnson",
      imageUrl: "https://i.pravatar.cc/150?img=1",
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      verified: true,
    },
    {
      productId: insertedProducts[15].id,
      rating: 5,
      comment: "Best headphones I've owned! Sound quality is incredible and battery lasts forever.",
      customerName: "Michael Chen",
      imageUrl: "https://i.pravatar.cc/150?img=12",
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      verified: true,
    },
    {
      productId: insertedProducts[30].id,
      rating: 5,
      comment: "My skin has never looked better! This brush is a game-changer.",
      customerName: "Sarah Martinez",
      imageUrl: "https://i.pravatar.cc/150?img=5",
      date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      verified: true,
    },
  ];

  const insertedReviews = await db.insert(schema.reviews).values(reviews).returning();
  console.log(`✓ Inserted ${insertedReviews.length} reviews`);

  // Seed Purchase Notifications with USA locations
  const notifications = [
    {
      customerName: "Jessica R.",
      location: "Los Angeles, CA",
      productName: "Classic Denim Jacket",
      timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    },
    {
      customerName: "David L.",
      location: "New York, NY",
      productName: "Wireless Noise-Canceling Headphones",
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    {
      customerName: "Amanda K.",
      location: "Chicago, IL",
      productName: "Vitamin C Serum",
      timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    },
  ];

  const insertedNotifications = await db.insert(schema.purchaseNotifications).values(notifications).returning();
  console.log(`✓ Inserted ${insertedNotifications.length} purchase notifications`);

  console.log("✅ Database seeding completed!");
}

export { seed };

// Only run if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seed().catch((error) => {
    console.error("Error seeding database:", error);
    process.exit(1);
  });
}
