import { db } from "./db";
import * as schema from "@shared/schema";

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(schema.purchaseNotifications);
  await db.delete(schema.reviews);
  await db.delete(schema.deals);
  await db.delete(schema.cartItems);
  await db.delete(schema.wishlistItems);
  await db.delete(schema.products);
  await db.delete(schema.categories);

  // Seed Categories
  const categories = [
    {
      name: "Fashion",
      slug: "fashion",
      imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800",
      description: "Traditional and contemporary fashion wear",
    },
    {
      name: "Electronics",
      slug: "electronics",
      imageUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800",
      description: "Latest gadgets and electronics",
    },
    {
      name: "Beauty & Wellness",
      slug: "beauty-wellness",
      imageUrl: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800",
      description: "Beauty and wellness products",
    },
    {
      name: "Furniture",
      slug: "furniture",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
      description: "Premium furniture for your home",
    },
    {
      name: "Food & Spices",
      slug: "food-spices",
      imageUrl: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800",
      description: "Authentic spices and gourmet foods",
    },
    {
      name: "Toys & Handicrafts",
      slug: "toys-handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800",
      description: "Handmade toys and crafts",
    },
    {
      name: "Pet Products",
      slug: "pet-products",
      imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
      description: "Products for your furry friends",
    },
    {
      name: "Healthcare & Supplements",
      slug: "healthcare",
      imageUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800",
      description: "Health and wellness supplements",
    },
  ];

  const insertedCategories = await db.insert(schema.categories).values(categories).returning();
  console.log(`✓ Inserted ${insertedCategories.length} categories`);

  // Seed Products with real images and variants
  const products = [
    // FASHION PRODUCTS (5 items)
    {
      name: "Banarasi Silk Saree - Wedding Collection",
      description: "Luxurious handwoven Banarasi silk saree with intricate golden zari work, perfect for weddings",
      price: "89.99",
      originalPrice: "149.99",
      discount: 40,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600",
      rating: "4.8",
      reviewCount: 342,
      inStock: true,
      stockCount: 25,
      tags: ["trending", "bestseller"],
      badge: "Bestseller",
      freeShipping: true,
      variants: ["Red", "Blue", "Green", "Maroon", "Pink"],
    },
    {
      name: "Designer Anarkali Kurta Set",
      description: "Elegant Anarkali kurta with embroidered dupatta and churidar, perfect for festive occasions",
      price: "45.99",
      originalPrice: "79.99",
      discount: 42,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1583391733981-5babf5773c04?w=600",
      rating: "4.6",
      reviewCount: 218,
      inStock: true,
      stockCount: 40,
      badge: "New Arrival",
      freeShipping: true,
      variants: ["S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Ethnic Embroidered Lehenga Choli",
      description: "Stunning lehenga choli with mirror work and sequins, ideal for weddings and celebrations",
      price: "129.99",
      originalPrice: "219.99",
      discount: 41,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1595777216082-c7fd2c1a0505?w=600",
      rating: "4.9",
      reviewCount: 167,
      inStock: true,
      stockCount: 15,
      badge: "Premium",
      freeShipping: true,
      variants: ["S", "M", "L", "XL"],
    },
    {
      name: "Cotton Printed Kurti",
      description: "Comfortable cotton kurti with block prints, perfect for daily wear",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600",
      rating: "4.4",
      reviewCount: 456,
      inStock: true,
      freeShipping: false,
      variants: ["S", "M", "L", "XL"],
    },
    {
      name: "Traditional Silk Dupatta",
      description: "Pure silk dupatta with golden border, complements any ethnic outfit",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Fashion",
      imageUrl: "https://images.unsplash.com/photo-1609873814058-a8928924184a?w=600",
      rating: "4.5",
      reviewCount: 128,
      inStock: true,
      freeShipping: true,
      variants: ["Red", "Blue", "Orange", "Purple", "Green"],
    },

    // ELECTRONICS PRODUCTS (5 items)
    {
      name: "Wireless Bluetooth Headphones - Premium Sound",
      description: "Active noise cancellation, 30-hour battery life, premium audio quality",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      stockCount: 50,
      badge: "Bestseller",
      freeShipping: true,
      variants: ["Black", "White", "Blue", "Red"],
    },
    {
      name: "Smart Watch - Fitness Tracker",
      description: "Heart rate monitor, sleep tracking, waterproof design, 7-day battery",
      price: "49.99",
      originalPrice: "99.99",
      discount: 50,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
      rating: "4.5",
      reviewCount: 634,
      inStock: true,
      stockCount: 75,
      badge: "Deal",
      freeShipping: true,
      variants: ["Black", "Silver", "Rose Gold"],
    },
    {
      name: "Portable Power Bank 20000mAh",
      description: "Fast charging, dual USB ports, LED display, compatible with all devices",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600",
      rating: "4.6",
      reviewCount: 423,
      inStock: true,
      freeShipping: false,
      variants: ["10000mAh", "20000mAh", "30000mAh"],
    },
    {
      name: "4K Action Camera - Waterproof",
      description: "4K video recording, waterproof up to 30m, wide-angle lens, WiFi enabled",
      price: "89.99",
      originalPrice: "159.99",
      discount: 44,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600",
      rating: "4.8",
      reviewCount: 256,
      inStock: true,
      badge: "New",
      freeShipping: true,
      variants: ["Black", "Silver", "With Accessories Kit"],
    },
    {
      name: "USB-C Fast Charging Cable - 6ft",
      description: "Durable braided cable, supports 60W fast charging, data transfer",
      price: "12.99",
      originalPrice: "19.99",
      discount: 35,
      category: "Electronics",
      imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600",
      rating: "4.4",
      reviewCount: 1024,
      inStock: true,
      freeShipping: false,
      variants: ["3ft", "6ft", "10ft", "2-Pack"],
    },

    // BEAUTY & WELLNESS PRODUCTS (5 items)
    {
      name: "Ayurvedic Face Cream - Natural Glow",
      description: "Organic ingredients, reduces wrinkles, brightens skin, suitable for all skin types",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600",
      rating: "4.7",
      reviewCount: 567,
      inStock: true,
      stockCount: 120,
      badge: "Bestseller",
      freeShipping: true,
      variants: ["50ml", "100ml", "150ml"],
    },
    {
      name: "Herbal Hair Oil - Anti Hair Fall",
      description: "Blend of 15 herbs, promotes hair growth, prevents dandruff, chemical-free",
      price: "18.99",
      originalPrice: "29.99",
      discount: 37,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600",
      rating: "4.6",
      reviewCount: 789,
      inStock: true,
      freeShipping: false,
      variants: ["100ml", "200ml", "500ml"],
    },
    {
      name: "Natural Turmeric Face Pack",
      description: "Pure turmeric powder, removes tan, brightens complexion, anti-bacterial",
      price: "14.99",
      originalPrice: "22.99",
      discount: 35,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600",
      rating: "4.8",
      reviewCount: 432,
      inStock: true,
      badge: "Natural",
      freeShipping: false,
      variants: ["50g", "100g", "200g"],
    },
    {
      name: "Aromatherapy Essential Oil Set",
      description: "6 premium oils: lavender, eucalyptus, peppermint, tea tree, lemon, rosemary",
      price: "34.99",
      originalPrice: "59.99",
      discount: 42,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600",
      rating: "4.9",
      reviewCount: 234,
      inStock: true,
      badge: "Premium",
      freeShipping: true,
      variants: ["6-Pack", "12-Pack", "Single Oils"],
    },
    {
      name: "Organic Aloe Vera Gel",
      description: "99% pure aloe vera, soothes skin, moisturizes, heals sunburn",
      price: "16.99",
      originalPrice: "26.99",
      discount: 37,
      category: "Beauty & Wellness",
      imageUrl: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=600",
      rating: "4.5",
      reviewCount: 678,
      inStock: true,
      freeShipping: false,
      variants: ["150ml", "300ml", "500ml"],
    },

    // FURNITURE PRODUCTS (4 items)
    {
      name: "Wooden Sheesham Dining Table",
      description: "Solid sheesham wood, seats 6 people, classic design, durable finish",
      price: "349.99",
      originalPrice: "599.99",
      discount: 42,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600",
      rating: "4.8",
      reviewCount: 145,
      inStock: true,
      stockCount: 8,
      badge: "Premium",
      freeShipping: true,
      variants: ["4-Seater", "6-Seater", "8-Seater"],
    },
    {
      name: "Velvet Upholstered Sofa - 3 Seater",
      description: "Premium velvet fabric, ergonomic design, solid wood frame, modern style",
      price: "499.99",
      originalPrice: "849.99",
      discount: 41,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
      rating: "4.7",
      reviewCount: 98,
      inStock: true,
      stockCount: 6,
      badge: "Bestseller",
      freeShipping: true,
      variants: ["Grey", "Blue", "Beige", "Green"],
    },
    {
      name: "Ergonomic Office Chair",
      description: "Adjustable height, lumbar support, breathable mesh, 360° swivel",
      price: "159.99",
      originalPrice: "249.99",
      discount: 36,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
      rating: "4.6",
      reviewCount: 423,
      inStock: true,
      freeShipping: true,
      variants: ["Black", "Grey", "Blue"],
    },
    {
      name: "Teak Wood Bookshelf - 5 Tier",
      description: "Solid teak wood, 5 spacious shelves, antique finish, handcrafted",
      price: "229.99",
      originalPrice: "379.99",
      discount: 39,
      category: "Furniture",
      imageUrl: "https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=600",
      rating: "4.7",
      reviewCount: 167,
      inStock: true,
      badge: "Handcrafted",
      freeShipping: true,
      variants: ["3-Tier", "5-Tier", "7-Tier"],
    },

    // FOOD & SPICES PRODUCTS (4 items)
    {
      name: "Organic Turmeric Powder - Premium Grade",
      description: "100% organic, high curcumin content, farm fresh, no additives",
      price: "12.99",
      originalPrice: "19.99",
      discount: 35,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600",
      rating: "4.8",
      reviewCount: 892,
      inStock: true,
      badge: "Organic",
      freeShipping: false,
      variants: ["100g", "250g", "500g", "1kg"],
    },
    {
      name: "Garam Masala Spice Blend",
      description: "Authentic blend of 12 spices, aromatic, perfect for curries and gravies",
      price: "9.99",
      originalPrice: "15.99",
      discount: 38,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1596040033229-a0b73e7d8eab?w=600",
      rating: "4.7",
      reviewCount: 634,
      inStock: true,
      freeShipping: false,
      variants: ["50g", "100g", "200g"],
    },
    {
      name: "Premium Basmati Rice - Aged",
      description: "1-year aged, extra-long grains, aromatic, perfect for biryanis",
      price: "24.99",
      originalPrice: "34.99",
      discount: 29,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600",
      rating: "4.9",
      reviewCount: 1234,
      inStock: true,
      badge: "Premium",
      freeShipping: true,
      variants: ["1kg", "5kg", "10kg"],
    },
    {
      name: "Assorted Indian Pickle Jar Set",
      description: "5 varieties: mango, lime, mixed veg, chili, garlic - traditional recipes",
      price: "29.99",
      originalPrice: "44.99",
      discount: 33,
      category: "Food & Spices",
      imageUrl: "https://images.unsplash.com/photo-1604999565976-8913ad2ddb7c?w=600",
      rating: "4.6",
      reviewCount: 456,
      inStock: true,
      badge: "Bestseller",
      freeShipping: true,
      variants: ["3-Pack", "5-Pack", "Individual"],
    },

    // TOYS & HANDICRAFTS PRODUCTS (4 items)
    {
      name: "Handmade Wooden Toy Train Set",
      description: "Non-toxic paint, smooth finish, eco-friendly, develops motor skills",
      price: "34.99",
      originalPrice: "54.99",
      discount: 36,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600",
      rating: "4.8",
      reviewCount: 234,
      inStock: true,
      badge: "Eco-Friendly",
      freeShipping: true,
      variants: ["Small", "Medium", "Large"],
    },
    {
      name: "Traditional Rajasthani Puppet Set",
      description: "Handcrafted string puppets, colorful costumes, set of 4 characters",
      price: "44.99",
      originalPrice: "69.99",
      discount: 36,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600",
      rating: "4.7",
      reviewCount: 145,
      inStock: true,
      badge: "Handcrafted",
      freeShipping: true,
      variants: ["2-Pack", "4-Pack", "6-Pack"],
    },
    {
      name: "Brass Home Decor Statue - Ganesha",
      description: "Antique brass finish, intricate detailing, auspicious home decor",
      price: "59.99",
      originalPrice: "99.99",
      discount: 40,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600",
      rating: "4.9",
      reviewCount: 312,
      inStock: true,
      badge: "Premium",
      freeShipping: true,
      variants: ["Small", "Medium", "Large"],
    },
    {
      name: "Madhubani Painting - Wall Art",
      description: "Hand-painted on canvas, traditional Bihar art, vibrant colors",
      price: "79.99",
      originalPrice: "129.99",
      discount: 38,
      category: "Toys & Handicrafts",
      imageUrl: "https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=600",
      rating: "4.8",
      reviewCount: 98,
      inStock: true,
      badge: "Handmade",
      freeShipping: true,
      variants: ["12x16 inch", "16x20 inch", "20x24 inch"],
    },

    // PET PRODUCTS (4 items)
    {
      name: "Premium Dog Food - Chicken & Rice",
      description: "High protein, grain-free option, supports healthy digestion, all breeds",
      price: "39.99",
      originalPrice: "59.99",
      discount: 33,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600",
      rating: "4.7",
      reviewCount: 678,
      inStock: true,
      badge: "Bestseller",
      freeShipping: true,
      variants: ["2kg", "5kg", "10kg", "15kg"],
    },
    {
      name: "Cat Scratching Post Tower",
      description: "Multi-level, sisal rope, plush bedding, hanging toys included",
      price: "49.99",
      originalPrice: "79.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600",
      rating: "4.6",
      reviewCount: 345,
      inStock: true,
      freeShipping: true,
      variants: ["Small", "Medium", "Large"],
    },
    {
      name: "Interactive Pet Toy Ball",
      description: "Automatic rolling, LED lights, rechargeable, keeps pets entertained",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1591769225440-811ad7d6eab3?w=600",
      rating: "4.5",
      reviewCount: 423,
      inStock: true,
      freeShipping: false,
      variants: ["Blue", "Pink", "Green"],
    },
    {
      name: "Comfortable Pet Bed - Orthopedic",
      description: "Memory foam, washable cover, anti-slip bottom, for dogs and cats",
      price: "44.99",
      originalPrice: "74.99",
      discount: 40,
      category: "Pet Products",
      imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600",
      rating: "4.8",
      reviewCount: 567,
      inStock: true,
      badge: "Comfort",
      freeShipping: true,
      variants: ["Small", "Medium", "Large", "X-Large"],
    },

    // HEALTHCARE & SUPPLEMENTS PRODUCTS (4 items)
    {
      name: "Ashwagandha Capsules - Stress Relief",
      description: "500mg per capsule, reduces stress, improves energy, 60 capsules",
      price: "19.99",
      originalPrice: "32.99",
      discount: 39,
      category: "Healthcare & Supplements",
      imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600",
      rating: "4.7",
      reviewCount: 892,
      inStock: true,
      badge: "Bestseller",
      freeShipping: false,
      variants: ["60 Capsules", "120 Capsules", "180 Capsules"],
    },
    {
      name: "Vitamin D3 + K2 Supplement",
      description: "Supports bone health, immune system, 5000 IU, 90 tablets",
      price: "16.99",
      originalPrice: "26.99",
      discount: 37,
      category: "Healthcare & Supplements",
      imageUrl: "https://images.unsplash.com/photo-1550572017-edd951b55104?w=600",
      rating: "4.6",
      reviewCount: 634,
      inStock: true,
      freeShipping: false,
      variants: ["30 Tablets", "60 Tablets", "90 Tablets"],
    },
    {
      name: "Omega-3 Fish Oil - Triple Strength",
      description: "2000mg per serving, supports heart health, purified, no fishy aftertaste",
      price: "29.99",
      originalPrice: "49.99",
      discount: 40,
      category: "Healthcare & Supplements",
      imageUrl: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600",
      rating: "4.8",
      reviewCount: 1023,
      inStock: true,
      badge: "Premium",
      freeShipping: true,
      variants: ["60 Softgels", "120 Softgels", "180 Softgels"],
    },
    {
      name: "Probiotic Blend - Digestive Health",
      description: "10 billion CFU, 10 strains, supports gut health, vegan capsules",
      price: "24.99",
      originalPrice: "39.99",
      discount: 38,
      category: "Healthcare & Supplements",
      imageUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600",
      rating: "4.7",
      reviewCount: 456,
      inStock: true,
      badge: "Natural",
      freeShipping: false,
      variants: ["30 Capsules", "60 Capsules", "90 Capsules"],
    },
  ];

  const insertedProducts = await db.insert(schema.products).values(products).returning();
  console.log(`✓ Inserted ${insertedProducts.length} products`);

  // Seed Flash Deals
  const deals = [
    {
      productId: insertedProducts[0].id,
      title: "Flash Sale: Banarasi Silk Saree",
      endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      productId: insertedProducts[5].id,
      title: "Limited Time: Wireless Headphones",
      endsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const insertedDeals = await db.insert(schema.deals).values(deals).returning();
  console.log(`✓ Inserted ${insertedDeals.length} deals`);

  // Seed Reviews
  const reviews = [
    {
      productId: insertedProducts[0].id,
      rating: 5,
      comment: "Amazing quality! The silk is so soft and the zari work is exquisite. Worth every penny!",
      customerName: "Priya Sharma",
      imageUrl: "https://i.pravatar.cc/150?img=1",
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      verified: true,
    },
    {
      productId: insertedProducts[5].id,
      rating: 5,
      comment: "Best headphones I've ever owned. The sound quality is incredible and battery lasts forever!",
      customerName: "Rajesh Kumar",
      imageUrl: "https://i.pravatar.cc/150?img=12",
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      verified: true,
    },
  ];

  const insertedReviews = await db.insert(schema.reviews).values(reviews).returning();
  console.log(`✓ Inserted ${insertedReviews.length} reviews`);

  // Seed Purchase Notifications
  const notifications = [
    {
      customerName: "Anjali M.",
      location: "Mumbai, Maharashtra",
      productName: "Banarasi Silk Saree",
      timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    },
    {
      customerName: "Rohit K.",
      location: "Delhi, NCR",
      productName: "Wireless Bluetooth Headphones",
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
  ];

  const insertedNotifications = await db.insert(schema.purchaseNotifications).values(notifications).returning();
  console.log(`✓ Inserted ${insertedNotifications.length} purchase notifications`);

  console.log("✅ Database seeding completed!");
}

export { seed };

// Only run if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seed().catch((error) => {
    console.error("Error seeding database:", error);
    process.exit(1);
  });
}
